insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10001,'USD','INR',65,'');
insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10002,'USD','INR',75,'');
insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10003,'USD','INR',85,'');